---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: network-host-device-static
spec:
  config: '{
    "cniVersion": "0.4.0",
    "name": "network-host-device-static",
    "type": "host-device",
    "device": "net99",
    "ipam": {
      "type": "static",
      "addresses":[
        {
          "address": "192.168.12.99/24",
          "gateway": "192.168.12.1"
        },
        {
          "address": "3ffe:ffff:0:01ff::1/64",
          "gateway": "3ffe:ffff:0::1"
        }
      ],
      "routes": [
        { "dst": "0.0.0.0/0" },
        { "dst": "192.168.0.0/16", "gw": "192.168.12.1" }
      ]
    }
  }'
---
apiVersion: v1
kind: Secret
metadata:
  name: bot-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJiVzFqYTJsbGNtNHJiVzFqYTJsbGNtNWZZbTkwT2taSE5UWkhNRlV5VlU5TVFUWmFOVFF6TkROQ1ZEQTFURkpYT1VjeVJUQXhRVlJIVTB4S1JrRlpXVXRCVjFBeU1qTlNXRWRLVEZaRFRrSTFRelZHVmtnPSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Pod
metadata:
  name: host-device-pod
spec:
  containers:
  - name: testapp
    image: quay.io/mmckiern/net-tools:latest
    imagePullPolicy: Always
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do ip a && sleep 30; done;" ]
  imagePullSecrets:
  - name: bot-pull-secret
