---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: network-ipvlan-static
spec:
  config: '{
    "cniVersion": "0.4.0",
    "name": "network-ipvlan-static",
    "type": "ipvlan",
    "master": "ens3",
    "mode": "l3",
    "ipam": {
      "type": "static",
      "addresses":[
        {
          "address": "192.168.12.99/24",
          "gateway": "192.168.12.1"
        }
      ]
    }
  }'
---
apiVersion: v1
kind: Secret
metadata:
  name: bot-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJiVzFqYTJsbGNtNHJiVzFqYTJsbGNtNWZZbTkwT2taSE5UWkhNRlV5VlU5TVFUWmFOVFF6TkROQ1ZEQTFURkpYT1VjeVJUQXhRVlJIVTB4S1JrRlpXVXRCVjFBeU1qTlNXRWRLVEZaRFRrSTFRelZHVmtnPSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Pod
metadata:
  name: ipvlan-static-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: network-ipvlan-static
spec:
  containers:
  - name: testapp
    image: quay.io/mmckiern/net-tools:latest
    imagePullPolicy: Always
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
  imagePullSecrets:
  - name: bot-pull-secret
