---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  annotations:
    metallb.universe.tf/address-pool: "gold"
spec:
  selector:
    app: hello-world
  ports:
    - port: 8080
  type: LoadBalancer
