apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: ci-ln-l9ts6qk-d5d6b-xmcc9-worker-us-east-1b
  namespace: openshift-machine-api
spec:
  template:
    spec:
      metadata:
        labels:
          type: "user-node"
          region: "east"
