apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mmckiern
resources:
- bases/networks-operator-cluster.yaml
- bot-pull-secret.yaml
- bridge-static-pod.yaml

patches:
- path: patches/add-network-bridge-static.yaml
  target:
    group: operator.openshift.io
    version: v1
    kind: Network
    name: cluster
