---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
 labels:
    operators.coreos.com/argocd-operator.argocd: ""
  name: argocd-operator
  namespace: argocd
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: argocd-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
