---
apiVersion: metallb.io/v1beta1
kind: AddressPool
metadata:
  name: doc-example-bgp-adv
  namespace: metallb-system
spec:
  protocol: bgp
  addresses:
    - 192.168.1.0/24
    - fc00:f853:0ccd:e799::/124
#  bgpAdvertisements:
#  - communities:
#    - 65535:65282
  bgpAdvertisements:
  - aggregationLength: 24
    aggregationLengthV6: 124
