---
apiVersion: v1
kind: Service
metadata:
  name: test-agnhost
  annotations:
    metallb.universe.tf/address-pool: doc-example-bgp-adv
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    run: test-agnhost
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
