---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: display-unconf
spec:
  selector:
    matchLabels:
      app: display-unconf
  template:
    metadata:
      labels:
        app: display-unconf
      annotations:
      generateName: display-unconf-
    spec:
      containers:
      - name: testapp
        image: quay.io/mmckiern/net-tools:latest
        imagePullPolicy: Always
        command: ["/bin/bash", "-c", "--"]
        args: ["echo 'hello'; pwd; echo '\n'; while true; do chroot /host && ls /usr/sbin/ip* && sleep 30; done;"]
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /host
            mountPropagation: HostToContainer
            name: host-slash
            readOnly: true
      volumes:
        - hostPath:
            path: /
            type: ""
          name: host-slash
      imagePullSecrets:
      - name: bot-pull-secret

