---
apiVersion: v1
kind: Service
metadata:
  name: invalid-request
spec:
  selector:
    run: test-agnhost
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 4.3.2.1
