---
apiVersion: metallb.io/v1alpha1
kind: AddressPool
metadata:
  namespace: metallb-system
  name: one
spec:
 protocol: layer2
 addresses:
 - 192.168.10.200/32
 autoAssign: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: special
spec:
  selector:
    matchLabels:
      run: special
  replicas: 1
  template:
    metadata:
      labels:
        run: special
    spec:
      containers:
        - args:
          - netexec
          image: k8s.gcr.io/e2e-test-images/agnhost:2.32
          name: agnhost
          ports:
            - containerPort: 8080
              protocol: TCP
      dnsConfig:
        nameservers:
          - 1.1.1.1
        searches:
          - resolv.conf.local
      dnsPolicy: None
---
apiVersion: v1
kind: Service
metadata:
  name: special-http
  annotations:
    metallb.universe.tf/address-pool: one
    metallb.universe.tf/allow-shared-ip: "web-server-svc"
spec:
  selector:
    app: special
  ports:
    - port: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: special-https
  annotations:
    metallb.universe.tf/address-pool: one
    metallb.universe.tf/allow-shared-ip: "web-server-svc"
spec:
  selector:
    app: special
  ports:
    - port: 443
  type: LoadBalancer
