apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 05-worker-kernelarg-pci-realloc
spec:
  config:
    ignition:
      version: 3.2.0
  kernelArguments:
    - pci=realloc
